import react,{useState} from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import ProductList from './components/productList';
import Navbar from './components/navbar';
export default function Home() {
  const [cart,setCart]=useState([]);
  const updateCart=value=>{
    setCart(value);
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <ProductList updateCart={updateCart}/>
      </main>
    </div>
  )
}
